[package]
name = "suins_auction"
edition = "2024.beta"

[dependencies]
suins = { local = "../suins" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

[addresses]
suins_auction = "0x0"
